server:
  port: 11011
bot:
  statusOk: ok
  confirmationCode: cc112ab5
  message:
    url: https://api.vk.com/method
    path: /messages.send
    chatIdParam: chat_id
    messageParam: message
    apiVersionParam: v
    apiVersionValue: 5.80
    tokenParam: access_token
    tokenValue: ""
  commands:
    getPlayers: /players
  conversations:
    test: "152240979"
    flud: ""
    officer: ""
    announcements: ""